backend:
  name: git-gateway
  branch: main
media_folder: "src/content"
public_folder: "/content"
collections:
  - name: "music"
    label: "Music"
    folder: "src/content/music"
    create: true
    slug: "{{sortOrder}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
